/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseAppLoading: typeof import('./../components/BaseAppLoading/BaseAppLoading.vue')['default']
    BaseBetterScroll: typeof import('./../components/BaseBetterScroll/BaseBetterScroll.vue')['default']
    BaseCard: typeof import('./../components/BaseCard/BaseCard.vue')['default']
    BaseCardLegend: typeof import('./../components/BaseCard/BaseCardLegend.vue')['default']
    BaseCardLegendTag: typeof import('./../components/BaseCard/BaseCardLegendTag.vue')['default']
    BaseCardPanel: typeof import('./../components/BaseCard/BaseCardPanel.vue')['default']
    BaseErrorPage: typeof import('./../components/BaseErrorPage/BaseErrorPage.vue')['default']
    BaseForm: typeof import('./../components/BaseForm/BaseForm.vue')['default']
    BaseHKVideo: typeof import('./../components/BaseHKVideo/BaseHKVideo.vue')['default']
    BaseHKVideoTool: typeof import('./../components/BaseHKVideo/BaseHKVideoTool.vue')['default']
    BaseHoverContainer: typeof import('./../components/BaseHoverContainer/BaseHoverContainer.vue')['default']
    BaseImageVerify: typeof import('./../components/BaseImageVerify/BaseImageVerify.vue')['default']
    BaseItemBackground: typeof import('./../components/BaseItemBackground/BaseItemBackground.vue')['default']
    BaseLoadingEmptyWrapper: typeof import('./../components/BaseLoadingEmptyWrapper/BaseLoadingEmptyWrapper.vue')['default']
    BaseLoginAgreement: typeof import('./../components/BaseLoginAgreement/BaseLoginAgreement.vue')['default']
    BaseMenu: typeof import('./../components/BaseMenu/BaseMenu.vue')['default']
    BaseModal: typeof import('./../components/BaseModal/BaseModal.vue')['default']
    BaseNaiveProvider: typeof import('./../components/BaseNaiveProvider/BaseNaiveProvider.vue')['default']
    BaseNaiveUiConfigProvider: typeof import('./../components/BaseNaiveProvider/BaseNaiveUiConfigProvider.vue')['default']
    BaseNumberAnimation: typeof import('./../components/BaseNumberAnimation/BaseNumberAnimation.vue')['default']
    BaseStatistic: typeof import('./../components/BaseStatistic/BaseStatistic.vue')['default']
    BaseSubtitle: typeof import('./../components/BaseSubtitle/BaseSubtitle.vue')['default']
    BaseSvgIcon: typeof import('./../components/BaseSvgIcon/BaseSvgIcon.vue')['default']
    BaseSystemLogo: typeof import('./../components/BaseSystemLogo/BaseSystemLogo.vue')['default']
    BaseWebSiteLink: typeof import('./../components/BaseWebSiteLink/BaseWebSiteLink.vue')['default']
    'BaseWrapContainerBorder-1': typeof import('./../components/BaseWrapContainer/BaseWrapContainerBorder-1.vue')['default']
    BaseWrapContainerBorder1: typeof import('./../components/BaseWrapContainer/BaseWrapContainerBorder-1.vue')['default']
    FastCrud: typeof import('@fast-crud/fast-crud')['FastCrud']
    FsCurd: typeof import('@fast-crud/fast-crud')['FsCurd']
    IconLocalNetworkError: typeof import('~icons/local/network-error')['default']
    IconLocalNoPermission: typeof import('~icons/local/no-permission')['default']
    IconLocalNotFound: typeof import('~icons/local/not-found')['default']
    IconLocalServiceError: typeof import('~icons/local/service-error')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SButton: typeof import('./../components/ScreenUiComponents/SButton.vue')['default']
    SCard: typeof import('./../components/ScreenUiComponents/SCard.vue')['default']
    SInput: typeof import('./../components/ScreenUiComponents/SInput.vue')['default']
    SModal: typeof import('./../components/ScreenUiComponents/SModal.vue')['default']
    STree: typeof import('./../components/ScreenUiComponents/STree.vue')['default']
    Tool: typeof import('./../components/BaseHKVideo/Tool.vue')['default']
    Video: typeof import('./../components/BaseHKVideo/Video.vue')['default']
    VideoTool: typeof import('./../components/BaseHKVideo/VideoTool.vue')['default']
    VideoView: typeof import('./../components/BaseHKVideo/VideoView.vue')['default']
  }
}
