/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BaseAppLoading: typeof import('./../components/BaseAppLoading/BaseAppLoading.vue')['default']
    BaseBetterScroll: typeof import('./../components/BaseBetterScroll/BaseBetterScroll.vue')['default']
    BaseCard: typeof import('./../components/BaseCard/BaseCard.vue')['default']
    BaseCardLegend: typeof import('./../components/BaseCard/BaseCardLegend.vue')['default']
    BaseCardPanel: typeof import('./../components/BaseCard/BaseCardPanel.vue')['default']
    BaseErrorPage: typeof import('./../components/BaseErrorPage/BaseErrorPage.vue')['default']
    BaseForm: typeof import('./../components/BaseForm/BaseForm.vue')['default']
    BaseHoverContainer: typeof import('./../components/BaseHoverContainer/BaseHoverContainer.vue')['default']
    BaseImageVerify: typeof import('./../components/BaseImageVerify/BaseImageVerify.vue')['default']
    BaseLayerTooltipCollapse: typeof import('./../components/BaseLayerTooltipCollapse/BaseLayerTooltipCollapse.vue')['default']
    BaseLayerTooltipCollapsePro: typeof import('./../components/BaseLayerTooltipCollapse/BaseLayerTooltipCollapsePro.vue')['default']
    BaseLoadingEmptyWrapper: typeof import('./../components/BaseLoadingEmptyWrapper/BaseLoadingEmptyWrapper.vue')['default']
    BaseLoginAgreement: typeof import('./../components/BaseLoginAgreement/BaseLoginAgreement.vue')['default']
    BaseMenu: typeof import('./../components/BaseMenu/BaseMenu.vue')['default']
    BaseModal: typeof import('./../components/BaseModal/BaseModal.vue')['default']
    BaseNaiveProvider: typeof import('./../components/BaseNaiveProvider/BaseNaiveProvider.vue')['default']
    BaseNaiveUiConfigProvider: typeof import('./../components/BaseNaiveProvider/BaseNaiveUiConfigProvider.vue')['default']
    BaseNumberAnimation: typeof import('./../components/BaseNumberAnimation.vue/BaseNumberAnimation.vue')['default']
    BaseSvgIcon: typeof import('./../components/BaseSvgIcon/BaseSvgIcon.vue')['default']
    BaseSystemLogo: typeof import('./../components/BaseSystemLogo/BaseSystemLogo.vue')['default']
    BaseWebSiteLink: typeof import('./../components/BaseWebSiteLink/BaseWebSiteLink.vue')['default']
    FastCrud: typeof import('@fast-crud/fast-crud')['FastCrud']
    FsCurd: typeof import('@fast-crud/fast-crud')['FsCurd']
    IconLocalNetworkError: typeof import('~icons/local/network-error')['default']
    IconLocalNoPermission: typeof import('~icons/local/no-permission')['default']
    IconLocalNotFound: typeof import('~icons/local/not-found')['default']
    IconLocalServiceError: typeof import('~icons/local/service-error')['default']
    IconMdiWechat: typeof import('~icons/mdi/wechat')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
