export { default as WidgetLeft } from './WidgetLeft.vue'
export { default as WidgetRight } from './WidgetRight.vue'
export { default as SliderPanels } from './SliderPanels/SliderPanels.vue'
export { default as SliderHeader } from './SliderPanels/SliderHeader.vue'
export { default as ControlLayer } from './ControlCollapse/ControlLayer.vue'
export { default as ControlLegend } from './ControlCollapse/ControlLegend.vue'
export { default as ControlParams } from './ControlCollapse/ControlParams.vue'
export { default as ControlTile } from './ControlCollapse/ControlTile.vue'
